cirrus_wheels_macos_arm64_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  env:
    MAKEFLAGS: -j4
    TWINE_USERNAME: ENCRYPTED[738d6df7ec92a5286c24060f1c48f1ab92c0efeb7883c814efff0cda1dcf62c8c1360f26cf5d96efeb124d0efeab4ec1]
    TWINE_PASSWORD: ENCRYPTED[e07ebded562c29c9fbbb9472e1e81944bcb1d4f27d82535d4ce398142becad5b058b2ebf139501e646db742cc22ed098]
  matrix:
    - env:
        PYVER: 3.8
        ABI: cp38
    - env:
        PYVER: 3.9
        ABI: cp39
    - env:
        PYVER: 3.10
        ABI: cp310
    - env:
        PYVER: 3.11
        ABI: cp311
    - env:
        PYVER: 3.12
        ABI: cp312
  build_script:
    ./build-wheels-macos.sh v1.22 ${ABI}
  upload_script:
    - ls -l wheelhouse/*.whl
    - if test -n "${CIRRUS_TAG}"; then python${PYVER} -m pip install twine && python${PYVER} -m twine upload wheelhouse/*.whl; fi
