cirrus_wheels_macos_arm64_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  env:
    MAKEFLAGS: -j4
    TWINE_USERNAME: ENCRYPTED[5cef4d5798a06ef1d2681e25b0e79f83dd63a64375c6ee9c66845cdd067c31d22d93e9656a9eec0def2c5da2e755466b]
    TWINE_PASSWORD: ENCRYPTED[9c02f4e5d0ee6ca807e6a00a5bafcc0611be9505975115b1ff39ca84f65cce5c48260a01cb43874c690b900b4699546e]
  matrix:
    - env:
        PYVER: 3.8
        ABI: cp38
    - env:
        PYVER: 3.9
        ABI: cp39
    - env:
        PYVER: 3.10
        ABI: cp310
    - env:
        PYVER: 3.11
        ABI: cp311
    - env:
        PYVER: 3.12
        ABI: cp312
  build_script:
    ./build-wheels-macos.sh openturns v1.23 ${ABI}
  upload_script:
    - ls -l wheelhouse/*.whl
    - if test -n "${CIRRUS_TAG}"; then python${PYVER} -m pip install twine --break-system-packages && python${PYVER} -m twine upload wheelhouse/*.whl; fi
