environment:
  VERSION: 1.17rc1
  matrix:
    - PYBASEVER: 3.6
      TAG: cp36-cp36m-win_amd64
    - PYBASEVER: 3.7
      TAG: cp37-cp37m-win_amd64
    - PYBASEVER: 3.8
      TAG: cp38-cp38-win_amd64
    - PYBASEVER: 3.9
      TAG: cp39-cp39-win_amd64

build_script:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - appveyor-retry appveyor DownloadFile https://github.com/openturns/build/releases/download/v%VERSION%/openturns-%VERSION%-py%PYBASEVER%-x86_64.exe
  - openturns-%VERSION%-py%PYBASEVER%-x86_64.exe /userlevel=1 /S /FORCE /D=%cd%\install
  - move %cd%\install\Lib\site-packages\openturns %cd%
  - move %cd%\install\Lib\site-packages\openturns-%VERSION%.dist-info %cd%
  - dir /p %cd%\openturns
  - python write_RECORD.py openturns %VERSION%
  - dir /p %cd%\openturns-%VERSION%.dist-info
  - 7z a -tzip openturns-%VERSION%-%TAG%.whl openturns openturns-%VERSION%.dist-info
  - call build-wheels-win32.bat otfftw 0.11 %PYBASEVER% %TAG%
  - call build-wheels-win32.bat otmixmod 0.12 %PYBASEVER% %TAG%
  - call build-wheels-win32.bat otmorris 0.10 %PYBASEVER% %TAG%
  - call build-wheels-win32.bat otpmml 1.11 %PYBASEVER% %TAG%
  - call build-wheels-win32.bat otrobopt 0.9 %PYBASEVER% %TAG%
  - call build-wheels-win32.bat otsubsetinverse 1.8 %PYBASEVER% %TAG%
  - call build-wheels-win32.bat otsvm 0.10 %PYBASEVER% %TAG%
  - dir /p %cd%
  - set PATH=C:\Miniconda36-x64;C:\Miniconda36-x64\Scripts;%PATH%
  - conda config --add channels conda-forge
  - conda update -y conda
  - conda create -y -n py%PYBASEVER% python=%PYBASEVER% pip twine
  - activate py%PYBASEVER%
  - pip install openturns --no-index --find-links=%CD%
  - python -c "import openturns as ot; print(ot.Normal(3).getRealization())"
  - pip install otfftw --no-index --find-links=%CD%
  - python -c "import otfftw; print(otfftw.__version__)"
  - pip install otmorris --no-index --find-links=%CD%
  - python -c "import otmorris; print(otmorris.__version__)"

after_build:
  - twine --version
  - IF DEFINED APPVEYOR_REPO_TAG_NAME twine upload --verbose openturns-%VERSION%-%TAG%.whl || echo "done"
  - IF DEFINED APPVEYOR_REPO_TAG_NAME twine upload --verbose ot*-%TAG%.whl || echo "done"

artifacts:
  - path: '**\*.whl'
    name: binary

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Windows wheels'
  provider: GitHub
  auth_token:
    secure: 4CkqK7ssPZsVuYY4gnYun8TlaVakivCHyw+EnT6z/KdoG3iTDcebHNdHQ+cYJFt+
  artifact: binary
  draft: false
  prerelease: false
  on:
    branch: /v.*/
    appveyor_repo_tag: true
