environment:
  VERSION: 1.12rc1
  matrix:
    - PYBASEVER: 2.7
      TAG: cp27-cp27m-win_amd64
    - PYBASEVER: 3.6
      TAG: cp36-cp36m-win_amd64
    - PYBASEVER: 3.7
      TAG: cp37-cp37m-win_amd64

build_script:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - appveyor-retry appveyor DownloadFile https://github.com/openturns/build/releases/download/v%VERSION%/openturns-%VERSION%-py%PYBASEVER%-x86_64.exe
  - openturns-%VERSION%-py%PYBASEVER%-x86_64.exe /userlevel=1 /S /FORCE /D=%cd%\install
  - move %cd%\install\Lib\site-packages\openturns %cd%
  - rm -r openturns\R-2.12.0 openturns\gs8.64 openturns\examples
  - dir /p %cd%\openturns
  - mkdir openturns-%VERSION%.dist-info
  - copy METADATA openturns-%VERSION%.dist-info
  - python write_WHEEL.py %VERSION% %TAG%
  - python write_RECORD.py %VERSION%
  - dir /p %cd%\openturns-%VERSION%.dist-info
  - 7z a -tzip openturns-%VERSION%-%TAG%.whl openturns openturns-%VERSION%.dist-info

artifacts:
  - path: openturns*.whl
    name: binary

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Windows wheels'
  provider: GitHub
  auth_token:
    secure: 4CkqK7ssPZsVuYY4gnYun8TlaVakivCHyw+EnT6z/KdoG3iTDcebHNdHQ+cYJFt+
  artifact: binary
  draft: false
  prerelease: false
  on:
    branch: /v.*/
    appveyor_repo_tag: true
