environment:
  VERSION: 1.14
  matrix:
    - PYBASEVER: 2.7
      TAG: cp27-cp27m-win_amd64
    - PYBASEVER: 3.6
      TAG: cp36-cp36m-win_amd64
    - PYBASEVER: 3.7
      TAG: cp37-cp37m-win_amd64
    - PYBASEVER: 3.8
      TAG: cp38-cp38-win_amd64

build_script:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - appveyor-retry appveyor DownloadFile https://github.com/openturns/build/releases/download/v%VERSION%/openturns-%VERSION%-py%PYBASEVER%-x86_64.exe
  - openturns-%VERSION%-py%PYBASEVER%-x86_64.exe /userlevel=1 /S /FORCE /D=%cd%\install
  - move %cd%\install\Lib\site-packages\openturns %cd%
  - move %cd%\install\Lib\site-packages\openturns-%VERSION%.dist-info %cd%
  - dir /p %cd%\openturns
  - python write_RECORD.py %VERSION%
  - dir /p %cd%\openturns-%VERSION%.dist-info
  - 7z a -tzip openturns-%VERSION%-%TAG%.whl openturns openturns-%VERSION%.dist-info
  - set PATH=C:\Miniconda36-x64;C:\Miniconda36-x64\Scripts;%PATH%
  - conda create -y -n py%PYBASEVER% python=%PYBASEVER% pip
  - activate py%PYBASEVER%
  - pip install openturns-%VERSION%-%TAG%.whl
  - python -c "import openturns as ot; print(ot.Normal(3).getRealization())"

artifacts:
  - path: openturns*.whl
    name: binary

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Windows wheels'
  provider: GitHub
  auth_token:
    secure: 4CkqK7ssPZsVuYY4gnYun8TlaVakivCHyw+EnT6z/KdoG3iTDcebHNdHQ+cYJFt+
  artifact: binary
  draft: false
  prerelease: false
  on:
    branch: /v.*/
    appveyor_repo_tag: true
