name: Nightly build
on:
  schedule:
    - cron:  '0 0 * * 5'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - abi: cp36m
         - abi: cp37m
         - abi: cp38
         - abi: cp39
    steps:
      - uses: actions/checkout@v2
      - name: Build wheel
        env:
          ABI: ${{ matrix.abi }}
        run: PYVER=${ABI:2:2} && docker pull openturns/manylinux1_x86_64 && docker run --rm -e MAKEFLAGS='-j2' -v `pwd`:/io openturns/manylinux1_x86_64 /io/build-wheels.sh git ${PYVER} ${ABI} manylinux1_x86_64
      - id: getfilename
        run: echo "::set-output name=file::$(ls wheelhouse/*.whl)"
      - name: Archive wheel
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: ${{ steps.getfilename.outputs.file }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Upload wheel
        shell: bash -l {0}
        run: |
          ls -l wheelhouse
          conda install -y anaconda-client
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u openturns-wheels-nightly wheelhouse/*.whl
