name: Nightly

on:
  schedule:
    - cron:  '0 0 * * 5'

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [cp38, cp39, cp310, cp311, cp312]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker pull openturns/manylinux2014_x86_64
          docker run --rm -e MAKEFLAGS='-j2' -v `pwd`:/io openturns/manylinux2014_x86_64 /io/build-wheels-linux.sh master ${{ matrix.abi }}
      - id: getfilename
        run: echo "::set-output name=file::$(ls wheelhouse/*.whl)"
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: ${{ steps.getfilename.outputs.file }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Upload
        shell: bash -l {0}
        run: |
          conda install -y anaconda-client
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u openturns-wheels-nightly wheelhouse/*.whl

  mingw:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [cp38, cp39, cp310, cp312]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker pull openturns/archlinux-mingw
          docker run --rm -e MAKEFLAGS='-j2' -v `pwd`:/io openturns/archlinux-mingw /io/build-wheels-mingw.sh master ${{ matrix.abi }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Upload
        shell: bash -l {0}
        run: |
          conda install -y anaconda-client
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u openturns-wheels-nightly wheelhouse/*.whl

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        abi: [cp38, cp39, cp310, cp311, cp312]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          MAKEFLAGS: -j3
        run: ./build-wheels-macos.sh master ${{ matrix.abi }}
      - id: getfilename
        run: echo "::set-output name=file::$(ls wheelhouse/*.whl)"
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: ${{ steps.getfilename.outputs.file }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Upload
        shell: bash -l {0}
        run: |
          conda install -y anaconda-client
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u openturns-wheels-nightly wheelhouse/*.whl
