name: Nightly

on:
  push:
  schedule:
    - cron:  '0 0 * * 5'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker pull openturns/manylinux2014_x86_64
          docker run --rm -e MAKEFLAGS='-j4' -v `pwd`:/io openturns/manylinux2014_x86_64 /io/build-wheels-linux.sh openturns master
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          conda-remove-defaults: "true"
      - name: Upload
        if: ${{ github.ref == 'refs/heads/master' }}
        shell: bash -l {0}
        run: |
          conda install -y anaconda-client
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u openturns-wheels-nightly wheelhouse/*.whl

  mingw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker pull openturns/archlinux-mingw
          docker run --rm -e MAKEFLAGS='-j4' -v `pwd`:/io openturns/archlinux-mingw /io/build-wheels-mingw.sh openturns master
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          conda-remove-defaults: "true"
      - name: Upload
        if: ${{ github.ref == 'refs/heads/master' }}
        shell: bash -l {0}
        run: |
          conda install -y anaconda-client
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u openturns-wheels-nightly wheelhouse/*.whl

  macos-x86_64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          MAKEFLAGS: -j3
        run: ./build-wheels-macos.sh openturns master 13
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          conda-remove-defaults: "true"
      - name: Upload
        if: ${{ github.ref == 'refs/heads/master' }}
        shell: bash -l {0}
        run: |
          conda install -y anaconda-client
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u openturns-wheels-nightly wheelhouse/*.whl

  macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          MAKEFLAGS: -j3
        run: ./build-wheels-macos.sh openturns master 14
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          conda-remove-defaults: "true"
      - name: Upload
        if: ${{ github.ref == 'refs/heads/master' }}
        shell: bash -l {0}
        run: |
          conda install -y anaconda-client
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force -u openturns-wheels-nightly wheelhouse/*.whl
